modLoader="javafml"
loaderVersion="[40,)"
license="GNU LGPL 3.0"

[[mods]]
modId="tfcagedalcohol"
version="${file.jarVersion}"
displayName="TFC Aged Alcohol"
credits = "Lumintorious"
authors = "HermitOwO"
description='''
Add aged alcohols with various effects to TFC.
'''

[[dependencies.tfcagedalcohol]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.tfcagedalcohol]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"

[[dependencies.tfcagedalcohol]]
modId = "tfc"
mandatory = true
versionRange = "[2.2.0,)"
ordering = "NONE"
side = "BOTH"